version: 1.12.0.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  lslversion: 1.13.0-b4
  LSLDIST_URL: "https://github.com/sccn/liblsl/releases/download"
  VCVER: 14.0
  QTVER: 5.12
  QTCOMPILER: msvc2015_64
  ARCH: x64
  CMakeArgs: ""
  DODEPLOY: false
install:
- cmd: appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip -FileName ninja.zip
- cmd: appveyor DownloadFile %LSLDIST_URL%/%lslversion%/liblsl-%lslversion%-Win64.7z -FileName liblsl_x64.7z
- cmd: 7z x ninja.zip -oC:\projects\deps\ninja > nul
- cmd: 7z x liblsl_x64.7z
- cmd: set PATH=C:\projects\deps\ninja;%PATH%
- cmd: ninja --version
build_script:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio %VCVER%\VC\vcvarsall.bat" %ARCH%
- mkdir build
- cd build
- cmd: cmake -G Ninja -DQt5_DIR=C:/Qt/%QTVER%/%QTCOMPILER%/lib/cmake/Qt5 -DBOOST_ROOT=C:/Libraries/boost_1_67_0 -DLSL_INSTALL_ROOT=LSL/ %CMakeArgs% ../
- cmake --build . --config Release --target install
- cpack
artifacts:
- path: build/install
  name: BrainVisionRDA_$(lslversion)-Win64
deploy:
- provider: BinTray
  username: tstenner
  api_key:
    secure: Fo9tIQnGjVnCXB3euItvYrt85A5O9FPqq7LEpsdOuwW+eOg1rwA5Q1HLp4yWDXAl
  subject: labstreaminglayer
  version: $(lslversion)
  repo: LSL
  package: BrainVisionRDA
  publish: true
  override: true
  on:
    dodeploy: true
